# Device-specific files are optional in redistribution-safe images.
install_optional_items+=" /usr/lib/firmware/updates/qcom/x1e80100/microsoft/qcdxkmsuc8380.mbn /usr/lib/firmware/updates/qcom/x1e80100/microsoft/Romulus/qcadsp8380.mbn /usr/lib/firmware/updates/qcom/x1e80100/microsoft/Romulus/qccdsp8380.mbn /usr/lib/firmware/updates/qcom/x1e80100/microsoft/Romulus/adsp_dtbs.elf /usr/lib/firmware/updates/qcom/x1e80100/microsoft/Romulus/cdsp_dtbs.elf "

